import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const  poppins = Poppins({
  weight: ['100', '200', '400', '600'],
  style: ['normal'],
  subsets:  ['latin']
})

export const metadata: Metadata = {
  title: 'Fotografer Samarinda',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className='max-w-lg mx-auto'>
          {children}
        </div>
      </body>
    </html>
  )
}
